import type { Product, Collection } from '@/types'

export const COLLECTIONS: Collection[] = [
  {
    id: '1',
    name: 'Lumière d\'été',
    slug: 'lumiere-dete',
    description: 'Notre première collection, inspirée par l\'éclat du soleil sur la mer.',
    image: '/images/collection-lumiere.jpg',
    featured: true,
    order: 1,
  },
  {
    id: '2',
    name: 'Colliers',
    slug: 'colliers',
    description: 'Des colliers délicats pour sublimer votre décolleté.',
    image: '/images/collection-colliers.jpg',
    featured: true,
    order: 2,
  },
  {
    id: '3',
    name: 'Bracelets',
    slug: 'bracelets',
    description: 'Des bracelets qui capturent l\'esprit de la plage.',
    image: '/images/collection-bracelets.jpg',
    featured: true,
    order: 3,
  },
  {
    id: '4',
    name: 'Boucles d\'oreilles',
    slug: 'boucles-doreilles',
    description: 'Des boucles légères comme une brise estivale.',
    image: '/images/collection-boucles.jpg',
    featured: true,
    order: 4,
  },
  {
    id: '5',
    name: 'Bagues',
    slug: 'bagues',
    description: 'Des bagues inspirées des trésors de la mer.',
    image: '/images/collection-bagues.jpg',
    featured: false,
    order: 5,
  },
]

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Collier Soleil d\'Or',
    slug: 'collier-soleil-dor',
    description: 'Un collier délicat en acier doré, orné d\'un soleil rayonnant. Symbole de lumière et d\'énergie estivale, ce bijou accompagnera vos journées les plus ensoleillées.',
    details: 'Matière : Acier inoxydable doré\nLongueur : 40 cm + 5 cm d\'extension\nPendentif : 1,5 cm\nHypoallergénique\nRésistant à l\'eau',
    price: 45,
    compareAt: 60,
    images: ['/images/collier-soleil-1.jpg', '/images/collier-soleil-2.jpg'],
    category: 'colliers',
    collection: 'lumiere-dete',
    material: 'Acier doré',
    inStock: true,
    featured: true,
    newArrival: true,
    variants: [
      { id: 'v1', productId: '1', name: '40 cm', sku: 'COL-SOL-40', stock: 15, price: null },
      { id: 'v2', productId: '1', name: '45 cm', sku: 'COL-SOL-45', stock: 8, price: null },
    ],
    createdAt: new Date(),
  },
  {
    id: '2',
    name: 'Bracelet Vague d\'Azur',
    slug: 'bracelet-vague-dazur',
    description: 'Un bracelet fin inspiré des vagues de la Méditerranée. Sa forme ondulée rappelle le mouvement doux de la mer par beau temps.',
    details: 'Matière : Argent sterling 925\nDiamètre : ajustable 15–19 cm\nFinition : rhodié\nHypoallergénique',
    price: 38,
    compareAt: null,
    images: ['/images/bracelet-vague-1.jpg', '/images/bracelet-vague-2.jpg'],
    category: 'bracelets',
    collection: 'lumiere-dete',
    material: 'Argent 925',
    inStock: true,
    featured: true,
    newArrival: true,
    variants: [],
    createdAt: new Date(),
  },
  {
    id: '3',
    name: 'Boucles Coquillage Nacré',
    slug: 'boucles-coquillage-nacre',
    description: 'Des boucles d\'oreilles en forme de coquillage, serties de nacre naturelle. Légères et lumineuses, elles évoquent les trésors du rivage.',
    details: 'Matière : Laiton doré + nacre naturelle\nDimension : 2 cm\nFermeture : clou avec poussette\nHypoallergénique',
    price: 32,
    compareAt: 42,
    images: ['/images/boucles-coquillage-1.jpg', '/images/boucles-coquillage-2.jpg'],
    category: 'boucles-doreilles',
    collection: 'lumiere-dete',
    material: 'Laiton doré + nacre',
    inStock: true,
    featured: true,
    newArrival: false,
    variants: [],
    createdAt: new Date(),
  },
  {
    id: '4',
    name: 'Bague Étoile de Mer',
    slug: 'bague-etoile-de-mer',
    description: 'Une bague ajustable ornée d\'une étoile de mer ciselée. Portez un peu de la magie des fonds marins à votre doigt.',
    details: 'Matière : Acier inoxydable doré\nTaille : ajustable (52–58)\nHypoallergénique\nRésistant à l\'eau',
    price: 28,
    compareAt: null,
    images: ['/images/bague-etoile-1.jpg', '/images/bague-etoile-2.jpg'],
    category: 'bagues',
    collection: 'lumiere-dete',
    material: 'Acier doré',
    inStock: true,
    featured: false,
    newArrival: true,
    variants: [],
    createdAt: new Date(),
  },
  {
    id: '5',
    name: 'Collier Perle de Lune',
    slug: 'collier-perle-de-lune',
    description: 'Un collier minimaliste orné d\'une perle d\'eau douce naturelle. Élégant et intemporel, il se porte seul ou superposé.',
    details: 'Matière : Argent sterling 925 + perle d\'eau douce\nLongueur : 42 cm\nPerle : 6–7 mm\nHypoallergénique',
    price: 52,
    compareAt: 68,
    images: ['/images/collier-perle-1.jpg', '/images/collier-perle-2.jpg'],
    category: 'colliers',
    collection: null,
    material: 'Argent 925 + perle',
    inStock: true,
    featured: true,
    newArrival: false,
    variants: [
      { id: 'v3', productId: '5', name: '40 cm', sku: 'COL-PER-40', stock: 6, price: null },
      { id: 'v4', productId: '5', name: '45 cm', sku: 'COL-PER-45', stock: 4, price: null },
    ],
    createdAt: new Date(),
  },
  {
    id: '6',
    name: 'Bracelet Corail Doré',
    slug: 'bracelet-corail-dore',
    description: 'Un bracelet coloré inspiré des coraux des mers chaudes. Ses perles orangées apportent une touche de soleil et de gaieté.',
    details: 'Matière : Perles de verre + fil en acier doré\nLongueur : 17 cm (avec fermoir)\nFermoir : mousqueton doré',
    price: 29,
    compareAt: null,
    images: ['/images/bracelet-corail-1.jpg'],
    category: 'bracelets',
    collection: null,
    material: 'Perles de verre + acier doré',
    inStock: true,
    featured: false,
    newArrival: true,
    variants: [],
    createdAt: new Date(),
  },
]

export const TESTIMONIALS = [
  {
    id: '1',
    name: 'Sophie L.',
    rating: 5,
    comment: 'Ces bijoux sont absolument magnifiques ! Le collier Soleil d\'Or est encore plus beau en vrai. L\'emballage était soigné et la livraison rapide. Je recommande à 100% !',
    product: 'Collier Soleil d\'Or',
    date: '15 mai 2026',
  },
  {
    id: '2',
    name: 'Camille M.',
    rating: 5,
    comment: 'J\'ai offert les boucles Coquillage à ma sœur pour son anniversaire. Elle était ravie ! La qualité est vraiment au rendez-vous pour ce prix.',
    product: 'Boucles Coquillage Nacré',
    date: '8 mai 2026',
  },
  {
    id: '3',
    name: 'Léa R.',
    rating: 5,
    comment: 'Le bracelet Vague d\'Azur est mon coup de cœur de l\'été ! Je le porte chaque jour, même à la plage, et il garde toute sa brillance.',
    product: 'Bracelet Vague d\'Azur',
    date: '2 mai 2026',
  },
]

export const ANNOUNCEMENTS = [
  '🚚 Livraison gratuite à partir de 60€',
  '🔒 Paiement 100% sécurisé',
  '✨ Nouvelle collection — Lumière d\'été disponible',
  '↩️ Retours gratuits sous 14 jours',
]
