import type { Product, Collection } from '@/types'

export const COLLECTIONS: Collection[] = [
  {
    id: '1',
    name: 'Lumière d\'été',
    slug: 'lumiere-dete',
    description: 'Notre première collection, inspirée par l\'éclat du soleil sur la mer.',
    image: '/images/collection-lumiere.jpg',
    featured: true,
    order: 1,
  },
  {
    id: '2',
    name: 'Colliers',
    slug: 'colliers',
    description: 'Des colliers délicats pour sublimer votre décolleté.',
    image: '/images/collection-colliers.jpg',
    featured: true,
    order: 2,
  },
  {
    id: '3',
    name: 'Bracelets',
    slug: 'bracelets',
    description: 'Des bracelets qui capturent l\'esprit de la plage.',
    image: '/images/collection-bracelets.jpg',
    featured: true,
    order: 3,
  },
  {
    id: '4',
    name: 'Boucles d\'oreilles',
    slug: 'boucles-doreilles',
    description: 'Des boucles légères comme une brise estivale.',
    image: '/images/collection-boucles.jpg',
    featured: true,
    order: 4,
  },
  {
    id: '5',
    name: 'Bagues',
    slug: 'bagues',
    description: 'Des bagues inspirées des trésors de la mer.',
    image: '/images/collection-bagues.jpg',
    featured: false,
    order: 5,
  },
]

/* Détails techniques communs — tous les bijoux sont en acier inoxydable */
const DETAILS_DORE =
  'Matière : Acier inoxydable doré\nHypoallergénique — sans nickel\nRésistant à l\'eau et au temps\nNe noircit pas, ne ternit pas'
const DETAILS_ARGENTE =
  'Matière : Acier inoxydable argenté\nHypoallergénique — sans nickel\nRésistant à l\'eau et au temps\nNe noircit pas, ne ternit pas'

export const PRODUCTS: Product[] = [
  /* ───────── Collection Lumière d'été ───────── */
  {
    id: '1',
    name: 'Collier Soléa',
    slug: 'collier-solea',
    description: 'Un collier délicat orné d\'un soleil rayonnant. Symbole de lumière et de chaleur estivale, il illumine chaque tenue d\'une touche dorée.',
    details: DETAILS_DORE + '\nLongueur : 40 cm + 5 cm d\'extension\nPendentif soleil : 1,2 cm',
    price: 18,
    compareAt: null,
    images: ['/images/products/collier-solea.jpg'],
    category: 'colliers',
    collection: 'lumiere-dete',
    material: 'Acier inoxydable doré',
    inStock: true,
    featured: true,
    newArrival: true,
    variants: [],
    createdAt: new Date(),
  },
  {
    id: '2',
    name: 'Bracelet Éclat Océan',
    slug: 'bracelet-eclat-ocean',
    description: 'Un bracelet à breloques inspiré des reflets de l\'océan. Ses pendentifs délicats dansent au moindre mouvement du poignet.',
    details: DETAILS_DORE + '\nTour de poignet : ajustable 16–19 cm\nFermoir mousqueton',
    price: 21,
    compareAt: null,
    images: ['/images/products/bracelet-eclat-ocean.jpg'],
    category: 'bracelets',
    collection: 'lumiere-dete',
    material: 'Acier inoxydable doré',
    inStock: true,
    featured: true,
    newArrival: false,
    variants: [],
    createdAt: new Date(),
  },
  {
    id: '3',
    name: 'Bague Trois Soleils',
    slug: 'bague-trois-soleils',
    description: 'Une bague ajustable ornée de trois petits soleils alignés. Un bijou lumineux qui rappelle les plus belles journées d\'été.',
    details: DETAILS_DORE + '\nTaille : ajustable (52–58)',
    price: 19,
    compareAt: null,
    images: ['/images/products/bague-trois-soleils.jpg'],
    category: 'bagues',
    collection: 'lumiere-dete',
    material: 'Acier inoxydable doré',
    inStock: true,
    featured: false,
    newArrival: true,
    variants: [],
    createdAt: new Date(),
  },
  {
    id: '4',
    name: 'Boucles d\'oreilles Lumia',
    slug: 'boucles-lumia',
    description: 'Des boucles d\'oreilles soleil, fines et lumineuses. Légères à porter, elles accompagnent vos journées du matin au soir.',
    details: DETAILS_DORE + '\nDimension : 1 cm\nFermeture : clou avec poussette',
    price: 18,
    compareAt: null,
    images: ['/images/products/boucles-lumia.jpg'],
    category: 'boucles-doreilles',
    collection: 'lumiere-dete',
    material: 'Acier inoxydable doré',
    inStock: true,
    featured: false,
    newArrival: true,
    variants: [],
    createdAt: new Date(),
  },

  /* ───────── Colliers ───────── */
  {
    id: '5',
    name: 'Collier Perla Bora',
    slug: 'collier-perla-bora',
    description: 'Un collier coquillage rehaussé d\'une perle nacrée. La douceur de la nacre rencontre l\'élégance du doré pour un bijou plein de poésie.',
    details: DETAILS_DORE + '\nLongueur : 42 cm + 5 cm d\'extension\nPendentif coquillage nacré',
    price: 22,
    compareAt: null,
    images: ['/images/products/collier-perla-bora.jpg'],
    category: 'colliers',
    collection: null,
    material: 'Acier inoxydable doré + nacre',
    inStock: true,
    featured: true,
    newArrival: false,
    variants: [],
    createdAt: new Date(),
  },
  {
    id: '9',
    name: 'Collier Siréna',
    slug: 'collier-sirena',
    description: 'Un collier argenté orné d\'une sirène et de coquillages ciselés. Un bijou enchanteur qui raconte les légendes de la mer.',
    details: DETAILS_ARGENTE + '\nLongueur : 42 cm + 5 cm d\'extension\nPendentif sirène et coquillages',
    price: 23,
    compareAt: null,
    images: ['/images/products/collier-sirena.jpg'],
    category: 'colliers',
    collection: null,
    material: 'Acier inoxydable argenté',
    inStock: true,
    featured: true,
    newArrival: false,
    variants: [],
    createdAt: new Date(),
  },
  {
    id: '14',
    name: 'Collier Nacré',
    slug: 'collier-nacre',
    description: 'Un collier minimaliste orné d\'une bille nacrée. Discret et intemporel, il se porte seul ou superposé à d\'autres chaînes.',
    details: DETAILS_DORE + '\nLongueur : 40 cm + 5 cm d\'extension\nBille nacrée : 6 mm',
    price: 18,
    compareAt: null,
    images: ['/images/products/collier-nacre.jpg'],
    category: 'colliers',
    collection: null,
    material: 'Acier inoxydable doré + nacre',
    inStock: true,
    featured: false,
    newArrival: false,
    variants: [],
    createdAt: new Date(),
  },

  /* ───────── Bracelets ───────── */
  {
    id: '6',
    name: 'Bracelet Vaïana',
    slug: 'bracelet-vaiana',
    description: 'Un bracelet à breloques fleuries, frais et romantique. Ses petites fleurs dorées évoquent les jardins gorgés de soleil.',
    details: DETAILS_DORE + '\nTour de poignet : ajustable 16–19 cm\nFermoir mousqueton',
    price: 23,
    compareAt: null,
    images: ['/images/products/bracelet-vaiana.jpg'],
    category: 'bracelets',
    collection: null,
    material: 'Acier inoxydable doré',
    inStock: true,
    featured: false,
    newArrival: true,
    variants: [],
    createdAt: new Date(),
  },
  {
    id: '10',
    name: 'Bracelet Ibiza',
    slug: 'bracelet-ibiza',
    description: 'Un bracelet argenté parsemé de coquillages délicats. Un esprit bohème et estival pour accompagner vos journées ensoleillées.',
    details: DETAILS_ARGENTE + '\nTour de poignet : ajustable 16–19 cm\nFermoir mousqueton',
    price: 17,
    compareAt: null,
    images: ['/images/products/bracelet-ibiza.jpg'],
    category: 'bracelets',
    collection: null,
    material: 'Acier inoxydable argenté',
    inStock: true,
    featured: false,
    newArrival: false,
    variants: [],
    createdAt: new Date(),
  },

  /* ───────── Bagues ───────── */
  {
    id: '7',
    name: 'Bague Bora Bora',
    slug: 'bague-bora-bora',
    description: 'Une bague argentée ornée d\'une étoile de mer scintillante. Portez un éclat des fonds marins au bout des doigts.',
    details: DETAILS_ARGENTE + '\nTaille : ajustable (52–58)\nMotif étoile de mer pavé',
    price: 18,
    compareAt: null,
    images: ['/images/products/bague-bora-bora.jpg'],
    category: 'bagues',
    collection: null,
    material: 'Acier inoxydable argenté',
    inStock: true,
    featured: false,
    newArrival: true,
    variants: [],
    createdAt: new Date(),
  },
  {
    id: '11',
    name: 'Bague Nouméa',
    slug: 'bague-noumea',
    description: 'Une bague à breloque coquillage, légère et estivale. Un petit trésor du rivage à porter chaque jour de l\'été.',
    details: DETAILS_DORE + '\nTaille : ajustable (52–58)\nBreloque coquillage',
    price: 18,
    compareAt: null,
    images: ['/images/products/bague-noumea.jpg'],
    category: 'bagues',
    collection: null,
    material: 'Acier inoxydable doré',
    inStock: true,
    featured: false,
    newArrival: false,
    variants: [],
    createdAt: new Date(),
  },

  /* ───────── Boucles d'oreilles ───────── */
  {
    id: '8',
    name: 'Boucles d\'oreilles Ibiza',
    slug: 'boucles-ibiza',
    description: 'Des boucles d\'oreilles ornées d\'une perle nacrée. Une élégance douce et lumineuse, parfaite en toute occasion.',
    details: DETAILS_DORE + '\nPerle nacrée : 8 mm\nFermeture : clou avec poussette',
    price: 18,
    compareAt: null,
    images: ['/images/products/boucles-ibiza.jpg'],
    category: 'boucles-doreilles',
    collection: null,
    material: 'Acier inoxydable doré + nacre',
    inStock: true,
    featured: false,
    newArrival: false,
    variants: [],
    createdAt: new Date(),
  },
  {
    id: '12',
    name: 'Boucles d\'oreilles Azura',
    slug: 'boucles-azura',
    description: 'Des boucles d\'oreilles fleuries, fraîches et délicates. Une touche de printemps qui dure tout l\'été.',
    details: DETAILS_DORE + '\nMotif fleur : 1 cm\nFermeture : clou avec poussette',
    price: 17,
    compareAt: null,
    images: ['/images/products/boucles-azura.jpg'],
    category: 'boucles-doreilles',
    collection: null,
    material: 'Acier inoxydable doré',
    inStock: true,
    featured: false,
    newArrival: false,
    variants: [],
    createdAt: new Date(),
  },
  {
    id: '13',
    name: 'Boucles d\'oreilles Nalia',
    slug: 'boucles-nalia',
    description: 'Des boucles d\'oreilles argentées coquillage et étoile de mer. Un duo marin qui évoque les balades pieds nus sur le sable.',
    details: DETAILS_ARGENTE + '\nMotifs coquillage et étoile de mer\nFermeture : clou avec poussette',
    price: 17,
    compareAt: null,
    images: ['/images/products/boucles-nalia.jpg'],
    category: 'boucles-doreilles',
    collection: null,
    material: 'Acier inoxydable argenté',
    inStock: true,
    featured: false,
    newArrival: false,
    variants: [],
    createdAt: new Date(),
  },
]

export const TESTIMONIALS = [
  {
    id: '1',
    name: 'Sophie L.',
    rating: 5,
    comment: 'Ces bijoux sont absolument magnifiques ! Le collier Soléa est encore plus beau en vrai. L\'emballage était soigné et la livraison rapide. Je recommande à 100% !',
    product: 'Collier Soléa',
    date: '15 mai 2026',
  },
  {
    id: '2',
    name: 'Camille M.',
    rating: 5,
    comment: 'J\'ai offert les boucles Lumia à ma sœur pour son anniversaire. Elle était ravie ! La qualité est vraiment au rendez-vous pour ce prix.',
    product: 'Boucles d\'oreilles Lumia',
    date: '8 mai 2026',
  },
  {
    id: '3',
    name: 'Léa R.',
    rating: 5,
    comment: 'Le bracelet Éclat Océan est mon coup de cœur de l\'été ! Je le porte chaque jour, même à la plage, et il garde toute sa brillance.',
    product: 'Bracelet Éclat Océan',
    date: '2 mai 2026',
  },
]

export const ANNOUNCEMENTS = [
  '🚚 Livraison gratuite à partir de 60€',
  '🔒 Paiement 100% sécurisé',
  '✨ Nouvelle collection — Lumière d\'été disponible',
  '↩️ Retours gratuits sous 14 jours',
]
